version: 2

updates:
  # Configure security updates for some package managers. This requires these repository settings:
  #   Code security and analysis > Dependabot > Dependabot alerts
  #   Code security and analysis > Dependabot > Dependabot security updates
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: Chore
      include: scope
    # Disable non-security updates, let Renovate handle it
    open-pull-requests-limit: 0
    labels: []
    # Disable rebasing, let .github/workflows/gh-automerge-rebase.yml handle it
    rebase-strategy: disabled
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: Chore
      include: scope
    # Disable non-security updates, let Renovate handle it
    open-pull-requests-limit: 0
    labels: [ ]
    # Disable rebasing, let .github/workflows/gh-automerge-rebase.yml handle it
    rebase-strategy: disabled
  # Note: .github/workflows/gh-dependabot-automerge.yml will auto-merge these PRs
