# https://github.com/EndBug/label-sync

# GitHub defaults
- name: bug
  description: A confirmed issues that needs fixing
  color: 'd73a4a'
#- name: dependencies
#  description: Pull requests that update a dependency file
#  color: '0366d6'
#- name: documentation
#  description: Improvements or additions to documentation
#  color: '0075ca'
- name: duplicate
  description: This issue or pull request already exists
  color: 'cfd3d7'
- name: enhancement
  description: New feature or request
  color: 'a2eeef'
#- name: good first issue
#  description: Good for newcomers
#  color: '7057ff'
#- name: help wanted
#  description: Extra attention is needed
#  color: '008672'
#- name: invalid
#  description: This doesn't seem right
#  color: 'e4e669'
- name: question
  description: Further information is requested
  color: 'd876e3'
#- name: wontfix
#  description: This will not be worked on
#  color: 'ffffff'

# https://github.com/temporalio/temporal/labels
#- name: feature-request
#  color: '4c2e9c'
#  alias: ['enhancement']
- name: potential-bug
  description: A potential issue that needs confirmation and/or triage
  color: '9f06e2'
- name: security
  color: 'f72e32'
- name: up-for-grabs
  description: Issues to consider for external contribution
  color: '66cc8d'

- name: hacktoberfest
  description: Issues that are a good candidate for a Hacktoberfest contribution
  color: 'ff8911'
- name: hacktoberfest-accepted
  description: Pull requests that should be counted for Hacktoberfest contributions but aren't ready to be merged
  color: 'ff8911'
- name: stale
  description: Issues that haven't had recent activity that will be automatically closed
  color: 'ffffff'
- name: ongoing
  description: Discussions to be kept open
  color: 'ffffff'

# Labels to control CI actions
- name: renovate/rebase
  description: Label to request a rebase from Renovate
  color: '318BE3'
