import path from 'node:path';

import moment from 'moment';

import ProgressBar from '../console/progressBar.js';
import Constants from '../constants.js';
import DAT from '../types/dats/dat.js';
import Game from '../types/dats/game.js';
import Header from '../types/dats/logiqx/header.js';
import LogiqxDAT from '../types/dats/logiqx/logiqxDat.js';
import ROM from '../types/dats/rom.js';
import ArchiveEntry from '../types/files/archives/archiveEntry.js';
import File from '../types/files/file.js';
import Module from './module.js';

/**
 * If no {@link DAT}s are provided, implicitly create some. A {@link DAT} will be created for every
 * subdirectory that contains files, and {@link Game}s will be named after each file's extracted
 * path (without the extension).
 *
 * This class will not be run concurrently with any other class.
 */
export default class DATGameInferrer extends Module {
  constructor(progressBar: ProgressBar) {
    super(progressBar, DATGameInferrer.name);
  }

  /**
   * Infer {@link Game}s from input files.
   */
  infer(romFiles: File[]): DAT[] {
    this.progressBar.logInfo(`inferring DATs for ${romFiles.length.toLocaleString()} ROM${romFiles.length !== 1 ? 's' : ''}`);

    const datNamesToRomFiles = romFiles.reduce((map, file) => {
      const datName = DATGameInferrer.getDatName(file);
      const datRomFiles = map.get(datName) ?? [];
      datRomFiles.push(file);
      map.set(datName, datRomFiles);
      return map;
    }, new Map<string, File[]>());
    this.progressBar.logDebug(`inferred ${datNamesToRomFiles.size.toLocaleString()} DAT${datNamesToRomFiles.size !== 1 ? 's' : ''}`);

    const dats = [...datNamesToRomFiles.entries()]
      .map(([datName, datRomFiles]) => DATGameInferrer.createDAT(datName, datRomFiles));

    this.progressBar.logInfo('done inferring DATs');
    return dats;
  }

  private static getDatName(file: File): string {
    return path.dirname(file.getFilePath()).split(/[\\/]/).slice(-1)[0];
  }

  private static createDAT(datName: string, romFiles: File[]): DAT {
    const date = moment().format('YYYYMMDD-HHmmss');
    const header = new Header({
      name: datName,
      description: datName,
      version: date,
      date,
      url: Constants.HOMEPAGE,
      comment: [
        `dir2dat generated by ${Constants.COMMAND_NAME} v${Constants.COMMAND_VERSION}`,
      ].join('\n'),
    });

    const gameNamesToRomFiles = romFiles.reduce((map, file) => {
      const gameName = DATGameInferrer.getGameName(file);
      const gameRomFiles = map.get(gameName) ?? [];
      gameRomFiles.push(file);
      map.set(gameName, gameRomFiles);
      return map;
    }, new Map<string, File[]>());

    const games = [...gameNamesToRomFiles.entries()].map(([gameName, gameRomFiles]) => {
      const roms = gameRomFiles.map((romFile) => new ROM({
        name: path.basename(romFile.getExtractedFilePath()),
        size: romFile.getSize(),
        crc: romFile.getCrc32(),
        md5: romFile.getMd5(),
        sha1: romFile.getSha1(),
      }));
      return new Game({
        name: gameName,
        description: gameName,
        rom: roms,
      });
    });

    return new LogiqxDAT(header, games);
  }

  private static getGameName(file: File): string {
    // Assume the game name is the filename
    let fileName = file.getExtractedFilePath();
    if (file instanceof ArchiveEntry) {
      // If the file is from an archive, assume the game name is the archive's filename
      fileName = file.getArchive().getFilePath();
    }

    return path.basename(fileName)
      .replace(/(\.[a-z0-9]+)+$/, '')
      .trim();
  }
}
