import moment from 'moment';

import ProgressBar, { ProgressBarSymbol } from '../console/progressBar.js';
import Constants from '../constants.js';
import DAT from '../types/logiqx/dat.js';
import Header from '../types/logiqx/header.js';
import Parent from '../types/logiqx/parent.js';
import Options from '../types/options.js';
import ReleaseCandidate from '../types/releaseCandidate.js';
import Module from './module.js';

export default class FixDATCreator extends Module {
  private readonly options: Options;

  constructor(options: Options, progressBar: ProgressBar) {
    super(progressBar, FixDATCreator.name);
    this.options = options;
  }

  async create(
    originalDat: DAT,
    parentsToCandidates: Map<Parent, ReleaseCandidate[]>,
  ): Promise<void> {
    await this.progressBar.logInfo(`${originalDat.getNameShort()}: generating a fixdat`);
    await this.progressBar.setSymbol(ProgressBarSymbol.WRITING);
    await this.progressBar.reset(1);

    // Create an easily searchable index of every ROM that has a ReleaseCandidate
    const writtenRomHashCodes = [...parentsToCandidates.values()]
      .flatMap((releaseCandidates) => releaseCandidates)
      .flatMap((releaseCandidate) => releaseCandidate.getRomsWithFiles())
      .map((romWithFiles) => romWithFiles.getRom())
      .reduce((map, rom) => {
        map.set(rom.hashCode(), true);
        return map;
      }, new Map<string, boolean>());
    // Find all the games who have at least one missing ROM
    const gamesWithMissingRoms = originalDat.getGames()
      .filter((game) => !game.getRoms().every((rom) => writtenRomHashCodes.has(rom.hashCode())));

    // Construct a new DAT header
    const date = moment().format('YYYYMMDD-HHmmss');
    const header = new Header({
      name: originalDat.getHeader().getName(),
      description: originalDat.getHeader().getDescription(),
      version: date,
      date,
      author: Constants.AUTHOR,
      url: Constants.HOMEPAGE,
      comment: `fixdat generated by ${Constants.COMMAND_NAME} v${Constants.COMMAND_VERSION}`,
    });

    // Construct a new DAT and write it to the output dir
    const fixdat = new DAT(header, gamesWithMissingRoms);
    this.options.getOutputDirParsed(fixdat);

    await this.progressBar.increment();
    await this.progressBar.logInfo(`${originalDat.getNameShort()}: done generating a fixdat`);
  }
}
