# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
# https://github.com/aio-libs/aiohttp/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
name: ðŸž Bug Report
description: Create a report to help us improve.
labels: ["potential-bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        _Please fill out the form below with as many precise details as possible._

  - type: textarea
    attributes:
      label: Paste the command
      description: |
        The exact Igir command you ran when you experienced a bug.

        Include the full `node`, `npm`, or `npx` command when not running the standalone `igir` executable.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Debug logs
      description: |
        The debug logs of your command run with the `-vvv` option. This is _not_ just a copy of the standard progress bar CLI output.

        You can redirect the CLI output of Igir to a file with the syntax: `igir [commands..] [options] -vvv > igir.log`. You can then attach this file in the GitHub text editor.

        This field is _not_ optional as it is one of the most important ways to gain insight into your unique scenario. Without this information it is difficult to reproduce your problem.
    validations:
      required: true

  - type: input
    attributes:
      label: DAT(s) used
      description: |
        Links to the DATs that were used for this Igir command, if any.

  - type: input
    attributes:
      label: igir version
      description: What version of Igir are you running? This is visible in the output header.
    validations:
      required: true

  - type: input
    attributes:
      label: Node.js version
      description: |
        What version of Node.js are you running? This can be seen with the `node --version` command.

        You can specify "N/A" when using a standalone version of Igir (one downloaded from GitHub).
    validations:
      required: true

  - type: input
    attributes:
      label: Operating system
      description: What operating system are you running?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.
