# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
# https://github.com/aio-libs/aiohttp/blob/master/.github/ISSUE_TEMPLATE/feature_request.yml
name: 🚀 Feature Request
description: Suggest an idea for this project.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking a minute to file a feature request!

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: |
        Please add a clear and concise description of what the problem is.

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

#  - type: textarea
#    attributes:
#      label: Describe alternatives you've considered
#      description: |
#        A clear and concise description of any alternative solutions or features you've considered.
#    validations:
#      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
