import crypto from 'node:crypto';
import events from 'node:events';
import fs from 'node:fs';
import path from 'node:path';
import type stream from 'node:stream';
import zlib from 'node:zlib';

import Temp from '../../../src/globals/temp.js';
import gracefulFs from '../../../src/polyfill/gracefulFs.js';
import FsUtil from '../../../src/utils/fsUtil.js';
import sevenZip, { SevenZipFormat } from '../index.js';

gracefulFs.gracefulify(fs);

const FIXTURE_DIR = path.join('packages', '7zip', 'test', 'fixtures');

/**
 * The format each fixture's extension names. Fixtures are grouped on disk by
 * what they CONTAIN rather than by format -- that is what lets one directory
 * carry one set of expectations -- so the format has to come from the file name
 * instead of from the directory it sits in. Each name also REPEATS its format as
 * a prefix -- `bz2-level1.bz2` -- so that a mixed-format directory reads as one
 * to a person, not only to `path.extname()`.
 */
const FORMATS_BY_EXTENSION = new Map<string, SevenZipFormat>([
  ['.7z', SevenZipFormat.SEVEN_ZIP],
  ['.zip', SevenZipFormat.ZIP],
  ['.Z', SevenZipFormat.Z],
  ['.bz2', SevenZipFormat.BZIP2],
  ['.lzma', SevenZipFormat.LZMA],
]);

interface Fixture {
  label: string;
  format: SevenZipFormat;
  archivePath: string;
}

/**
 * Every archive in one fixture directory, in a stable order. Adding a fixture
 * is therefore committing the file: it joins the tests parametrized over its
 * directory with no code change, and an extension nothing maps to fails loudly
 * here rather than being silently skipped.
 */
function fixtures(directory: string): Fixture[] {
  return fs
    .readdirSync(path.join(FIXTURE_DIR, directory))
    .toSorted((a, b) => a.localeCompare(b))
    .map((file) => {
      const format = FORMATS_BY_EXTENSION.get(path.extname(file));
      if (format === undefined) {
        throw new Error(`no format is mapped to the extension of fixture: ${file}`);
      }
      return {
        label: path.join(directory, file),
        format,
        archivePath: path.join(FIXTURE_DIR, directory, file),
      };
    });
}

/**
 * Every archive holding the same four entries, `1kb` through `4kb`. The `.7z`
 * fixtures share one payload; the zstd zips carry a compressible one instead,
 * so that method 93 exercises zstd's literal and sequence decoders rather than
 * emitting raw blocks. Nothing here compares bytes across archives -- each entry
 * is checked against the CRC32 its own archive records.
 *
 * The zips are zips rather than `.7z` because zstd is not a 7z method: 7-Zip
 * registers no codec for it, and the addon reaches its decoder only through
 * ZipHandler.cpp's branch for compression method 93.
 */
const MULTI_ENTRY_ARCHIVES = fixtures('four-small-files');

/**
 * Formats that wrap one nameless stream instead of a directory of entries. They
 * all compress the same 4 KiB payload, so one size and one CRC32 cover every one
 * of them.
 */
const SINGLE_STREAM_ARCHIVES = fixtures('one-small-file');

// The payload every single-stream fixture holds, as generated by
// `fixtures/generate.sh`.
const SINGLE_STREAM_SIZE = 4096;
const SINGLE_STREAM_CRC32 = '266df1c3';

/**
 * A 7z holding one 8 MiB entry. LZMA2 specifically: its decoder writes up to
 * 1 MiB per call into the addon's output sink, which is what lets a single
 * decoder call fill the read-ahead queue outright.
 *
 * The payload is compressible on purpose -- 8 MiB in, about 1.5 KiB committed,
 * unlike the keystream payloads every other fixture uses -- but its 251-byte
 * period is position-dependent, so the bytes read back can be verified rather
 * than only counted.
 */
const LARGE_ENTRY_ARCHIVES = fixtures('one-large-file');
const LARGE_ENTRY_PATH = '8mb';
const LARGE_ENTRY_SIZE = 8 * 1024 * 1024;

/**
 * One four-entry archive of a given format, for the tests that need a valid
 * archive to damage or to mis-open rather than every archive of that shape.
 */
function multiEntryArchive(format: SevenZipFormat): string {
  const fixture = MULTI_ENTRY_ARCHIVES.find((candidate) => candidate.format === format);
  if (fixture === undefined) {
    throw new Error(`no four-entry fixture exists for format: ${format}`);
  }
  return fixture.archivePath;
}

const SEVEN_ZIP_ARCHIVE = multiEntryArchive(SevenZipFormat.SEVEN_ZIP);
const ZIP_ARCHIVE = multiEntryArchive(SevenZipFormat.ZIP);

/**
 * `four-small-files/7z-copy.7z` sliced into 4 KiB volumes by `split`. Only the
 * first slice is ever named: 7-Zip's `Split` handler derives `.002`, `.003` and
 * so on itself. Listing it yields one entry -- the slices joined back together
 * -- which is why this is not part of {@link MULTI_ENTRY_ARCHIVES} despite being
 * built from an archive that holds four, and why it keeps a directory of its own
 * rather than joining one named for the entries it does not expose.
 */
const SPLIT_FIRST_VOLUME = path.join(FIXTURE_DIR, 'split', 'copy.7z.001');
const SPLIT_JOINED = path.join(FIXTURE_DIR, 'four-small-files', '7z-copy.7z');

/**
 * A true multi-disk zip from Info-ZIP's `zip -s`, which is a different thing
 * from the byte-sliced `split/` fixture: the final disk is named `.zip` and
 * carries the central directory, the earlier ones are `.z01`/`.z02`, and the
 * first opens with the 4-byte spanning marker.
 *
 * Only the last disk is named here. It is the one holding the central
 * directory, and it is the disk 7-Zip expects to be handed; it walks back to
 * `.z01` and `.z02` through the addon's open callback.
 *
 * This keeps a directory of its own for the same reason `split/` does, with one
 * more constraint: `zip` refuses a split size below 64 KiB, so a spanned archive
 * cannot be built out of the four small files at all -- its members have to be
 * large enough to straddle a disk.
 */
const SPANNED_LAST_DISK = path.join(FIXTURE_DIR, 'spanned', 'spanned.zip');
/**
 * Both members, in archive order. `first.bin` runs past the end of the second
 * disk, so `second.bin`'s local header begins on disk 2 and its
 * central-directory record carries `disk-number-start=2` with a local-header
 * offset relative to that disk rather than to the joined stream. Resolving that
 * pair back to an absolute offset is the arithmetic a single-member archive
 * never exercises.
 */
const SPANNED_ENTRIES = [
  { entryPath: 'first.bin', size: 140_000, crc32: '211e7a1d' },
  { entryPath: 'second.bin', size: 40_000, crc32: '9812a804' },
];

/**
 * Comfortably more than the addon's read-ahead bound, so the producer thread
 * blocks on a full queue and the queue turns over many times, while staying
 * small enough to build and drain quickly in CI.
 */
const LARGE_CONTENTS = crypto.randomBytes(8 * 1024 * 1024);

/**
 * Every chunk the stream emitted, in order. Kept separate from {@link drain}
 * because the sizes are themselves a contract -- see the high-watermark tests.
 */
async function collectChunks(readable: stream.Readable): Promise<Buffer[]> {
  const chunks: Buffer[] = [];
  for await (const chunk of readable) {
    chunks.push(chunk as Buffer);
  }
  return chunks;
}

async function drain(readable: stream.Readable): Promise<Buffer> {
  return Buffer.concat(await collectChunks(readable));
}

/**
 * Run `callback` against a temporary directory that is removed afterwards,
 * however it finishes.
 *
 * Setup and teardown are per-test and scoped by this rather than by
 * `beforeAll`/`afterAll` hooks. Vitest runs this suite shuffled, so anything two
 * tests share is state whose contents at any given moment depend on an order
 * that is deliberately not fixed; a helper that hands each test its own
 * directory has no such ordering to reason about, and the cleanup cannot be
 * skipped by a failure earlier in the file.
 */
async function withTempDir<T>(callback: (directory: string) => Promise<T> | T): Promise<T> {
  if (!(await FsUtil.exists(Temp.getTempDir()))) {
    await FsUtil.mkdir(Temp.getTempDir(), { recursive: true });
  }
  const directory = await FsUtil.mkdtemp(Temp.getTempDir());
  try {
    return await callback(directory);
  } finally {
    await FsUtil.rm(directory, { recursive: true, force: true });
  }
}

/**
 * Run `callback` against a freshly written stored ZIP holding
 * {@link LARGE_CONTENTS}. Stored entries need no encoder, so writing 8 MiB per
 * test costs a memcpy and a file write -- cheaper than the extraction each of
 * these tests then performs, and worth it to keep every test independent.
 */
async function withLargeArchive(callback: (archivePath: string) => Promise<void>): Promise<void> {
  await withTempDir(async (directory) => {
    const archivePath = path.join(directory, 'stored.zip');
    await writeStoredZip(archivePath, 'stored.bin', LARGE_CONTENTS);
    await callback(archivePath);
  });
}

// Node's crypto has no 'crc32' digest, but zlib.crc32() has been available
// since Node v20.15.0, comfortably below this package's engines floor.
function crc32Hex(buffer: Buffer): string {
  return zlib.crc32(buffer).toString(16).padStart(8, '0');
}

interface StoredZipOptions {
  /**
   * Prefix the file with NSignature::kSpan, the four bytes `zip -s` writes at
   * the front of a spanned archive. The file is otherwise a perfectly ordinary
   * single-volume ZIP -- the marker alone is what puts 7-Zip's Zip handler onto
   * its span-mode path.
   */
  hasSpanMarker?: boolean;
  /**
   * The compression method both headers declare. The payload is always written
   * verbatim, so anything other than 0 (stored) describes bytes that are not
   * what it claims -- which is the point: 7-Zip picks its decoder from this
   * number, and a number no registered codec answers to is how an archive with
   * a method this build cannot handle is produced without shipping one.
   */
  method?: number;
  /** The general-purpose bit flag both headers declare; bit 0 means encrypted. */
  flags?: number;
}

/**
 * Write a ZIP that stores every payload uncompressed (method 0). Stored entries
 * need no encoder, so a large archive can be produced here at test time rather
 * than committed as a binary fixture -- and so can a deliberately broken one, by
 * lying in the headers about what the payload is.
 */
async function writeStoredZipEntries(
  filePath: string,
  entries: { entryName: string; contents: Buffer }[],
  { hasSpanMarker = false, method = 0, flags = 0 }: StoredZipOptions = {},
): Promise<void> {
  const prefix = Buffer.alloc(hasSpanMarker ? 4 : 0);
  if (hasSpanMarker) {
    prefix.writeUInt32LE(0x08_07_4b_50, 0); // NSignature::kSpan
  }

  const locals: Buffer[] = [];
  const centrals: Buffer[] = [];
  let offset = prefix.length;
  for (const { entryName, contents } of entries) {
    const name = Buffer.from(entryName, 'utf8');
    const crc = zlib.crc32(contents);
    const size = contents.length;

    const localHeader = Buffer.alloc(30);
    localHeader.writeUInt32LE(0x04_03_4b_50, 0); // local file header signature
    localHeader.writeUInt16LE(20, 4); // version needed to extract
    localHeader.writeUInt16LE(flags, 6); // general purpose bit flag
    localHeader.writeUInt16LE(method, 8); // compression method
    localHeader.writeUInt32LE(crc, 14);
    localHeader.writeUInt32LE(size, 18); // compressed size
    localHeader.writeUInt32LE(size, 22); // uncompressed size
    localHeader.writeUInt16LE(name.length, 26);

    const centralHeader = Buffer.alloc(46);
    centralHeader.writeUInt32LE(0x02_01_4b_50, 0); // central directory signature
    centralHeader.writeUInt16LE(20, 4); // version made by
    centralHeader.writeUInt16LE(20, 6); // version needed to extract
    centralHeader.writeUInt16LE(flags, 8); // general purpose bit flag
    centralHeader.writeUInt16LE(method, 10); // compression method
    centralHeader.writeUInt32LE(crc, 16);
    centralHeader.writeUInt32LE(size, 20);
    centralHeader.writeUInt32LE(size, 24);
    centralHeader.writeUInt16LE(name.length, 28);
    centralHeader.writeUInt32LE(offset, 42); // local header offset

    locals.push(localHeader, name, contents);
    centrals.push(centralHeader, name);
    offset += localHeader.length + name.length + size;
  }

  const centralSize = centrals.reduce((total, chunk) => total + chunk.length, 0);
  const endOfCentralDirectory = Buffer.alloc(22);
  endOfCentralDirectory.writeUInt32LE(0x06_05_4b_50, 0); // end of central directory signature
  endOfCentralDirectory.writeUInt16LE(entries.length, 8); // entries on this disk
  endOfCentralDirectory.writeUInt16LE(entries.length, 10); // entries total
  endOfCentralDirectory.writeUInt32LE(centralSize, 12);
  endOfCentralDirectory.writeUInt32LE(offset, 16);

  await FsUtil.writeFile(
    filePath,
    Buffer.concat([prefix, ...locals, ...centrals, endOfCentralDirectory]),
  );
}

/**
 * {@link writeStoredZipEntries} for the common case of one entry.
 */
async function writeStoredZip(
  filePath: string,
  entryName: string,
  contents: Buffer,
  options: StoredZipOptions = {},
): Promise<void> {
  await writeStoredZipEntries(filePath, [{ entryName, contents }], options);
}

describe('listEntries', () => {
  test('it has fixtures to test', () => {
    expect(MULTI_ENTRY_ARCHIVES.length).toEqual(12);
    expect(SINGLE_STREAM_ARCHIVES.length).toEqual(5);
    expect(LARGE_ENTRY_ARCHIVES.length).toEqual(1);
  });

  test.each(MULTI_ENTRY_ARCHIVES)(
    'it lists the four entries in $label',
    async ({ format, archivePath }) => {
      const entries = await sevenZip.listEntries({ inputFilename: archivePath, format });
      expect(entries.map((entry) => entry.entryPath)).toEqual(['1kb', '2kb', '3kb', '4kb']);
      expect(entries.map((entry) => entry.size)).toEqual([1024, 2048, 3072, 4096]);
      // Compared as arrays rather than collapsed with every(), so a failure
      // names the entry that disagreed instead of reporting `false !== true`.
      expect(entries.map((entry) => /^[\da-f]{8}$/.test(entry.crc32 ?? ''))).toEqual([
        true,
        true,
        true,
        true,
      ]);
      expect(entries.map((entry) => entry.isDirectory)).toEqual([false, false, false, false]);
      expect(entries.map((entry) => entry.isEncrypted)).toEqual([false, false, false, false]);
      // The archive's own item indices. They happen to match this array's
      // positions here because no entry is filtered out, which is exactly why
      // the directory case below is worth its own assertion.
      expect(entries.map((entry) => entry.entryIndex)).toEqual([0, 1, 2, 3]);
    },
  );

  test.each(SINGLE_STREAM_ARCHIVES)(
    'it lists one nameless entry in $label',
    async ({ format, archivePath }) => {
      const entries = await sevenZip.listEntries({ inputFilename: archivePath, format });
      expect(entries.length).toEqual(1);
      // None of these containers records the member's name, size, or CRC32, so
      // the addon has nothing to report for them. The decompressed bytes are
      // still exact; `openEntryReader` proves that.
      expect(entries[0].entryPath).toBeUndefined();
      // Undefined, not 0: these formats record no length, and 0 is a real
      // length an empty member could legitimately have.
      expect(entries[0].size).toBeUndefined();
      expect(entries[0].crc32).toBeUndefined();
      expect(entries[0].isDirectory).toEqual(false);
      expect(entries[0].isEncrypted).toEqual(false);
      expect(entries[0].entryIndex).toEqual(0);
    },
  );

  test('it finds the rest of a split set from the first volume alone', async () => {
    // The whole point of the Split handler: `copy.7z.002` and `copy.7z.003` are
    // never named here. 7-Zip derives them from `.001` and pulls them through
    // the addon's IArchiveOpenVolumeCallback, which is also the interface
    // SplitHandler.cpp:126-133 refuses to open without.
    const entries = await sevenZip.listEntries({
      inputFilename: SPLIT_FIRST_VOLUME,
      format: SevenZipFormat.SPLIT,
    });
    expect(entries.map((entry) => entry.entryPath)).toEqual(['copy.7z']);
    // One entry, whose size is every slice added together -- the joined archive,
    // not the four entries inside it.
    expect(entries.map((entry) => entry.size)).toEqual([await FsUtil.size(SPLIT_JOINED)]);
  });

  test('it finds the earlier disks of a multi-disk zip from the last alone', async () => {
    // `spanned.z01` and `spanned.z02` are never named. Handing over only the
    // disk that carries the central directory is what a caller naturally has,
    // and ordering volumes by hand -- which used to be required, and silently
    // mis-extracted when wrong -- is no longer possible to get wrong.
    const entries = await sevenZip.listEntries({
      inputFilename: SPANNED_LAST_DISK,
      format: SevenZipFormat.ZIP,
    });
    expect(entries.map((entry) => entry.entryPath)).toEqual(
      SPANNED_ENTRIES.map((entry) => entry.entryPath),
    );
    expect(entries.map((entry) => entry.size)).toEqual(SPANNED_ENTRIES.map((entry) => entry.size));
    expect(entries.map((entry) => entry.crc32)).toEqual(
      SPANNED_ENTRIES.map((entry) => entry.crc32),
    );
  });

  test('it opens a single-volume zip that carries the span marker', async () => {
    // Regression test for a process-killing SIGSEGV, not a correctness nicety.
    // 7-Zip's CInArchive::Open has two ReadVols() call sites; only the first is
    // guarded by a non-null callback, and the span-mode one is not. Reaching it
    // with a null IArchiveOpenCallback dereferences null in ReadVols (ZipIn.cpp
    // :2337).
    //
    // Verified to exit 139 against a build that passes nullptr, and to pass
    // against the shipped one. If this ever regresses it takes the whole Vitest
    // worker down rather than failing an assertion -- that is the nature of the
    // bug, and a loud death is still a caught regression.
    await withTempDir(async (directory) => {
      const archive = path.join(directory, 'span.zip');
      await writeStoredZip(archive, 'a.txt', Buffer.from('hello span mode'), {
        hasSpanMarker: true,
      });
      const entries = await sevenZip.listEntries({
        inputFilename: archive,
        format: SevenZipFormat.ZIP,
      });
      expect(entries.length).toBeGreaterThanOrEqual(1);
      expect(entries[0].entryPath).toEqual('a.txt');
    });
  });

  test('it rejects a path it cannot open', async () => {
    // A missing file, an empty path, and a directory fail for three different
    // reasons inside the addon, but all three are "the caller named something
    // unopenable" and none needs its own fixture or setup.
    await expect(
      sevenZip.listEntries({
        inputFilename: path.join(FIXTURE_DIR, 'nope.7z'),
        format: SevenZipFormat.SEVEN_ZIP,
      }),
    ).rejects.toThrow(/could not read/);
    await expect(
      sevenZip.listEntries({ inputFilename: '', format: SevenZipFormat.SEVEN_ZIP }),
    ).rejects.toThrow(/path or format is invalid/);
    // A directory fails at a different point on each platform -- Windows will
    // not open one at all, POSIX opens it and fails on the first read -- so the
    // two get different messages, one the addon's own wording and one the
    // operating system's ("Is a directory"). What both have to say, and all
    // that is worth pinning down, is that a directory is what went wrong.
    await expect(
      sevenZip.listEntries({ inputFilename: FIXTURE_DIR, format: SevenZipFormat.SEVEN_ZIP }),
    ).rejects.toThrow(/directory/i);
  });

  test('it rejects a file that is not the archive it was opened as', async () => {
    // Everything a caller can hand a handler that is not an archive of that
    // format: noise, nothing at all, half of a real archive, and a real archive
    // of a different format. 7-Zip answers all four with S_FALSE -- it read the
    // file and decided it is not one of these -- so all four share one message,
    // and asserting them together is what shows that none of them crashes,
    // hangs, or is mistaken for a readable archive.
    await withTempDir(async (directory) => {
      const garbage = path.join(directory, 'garbage.7z');
      await FsUtil.writeFile(garbage, crypto.randomBytes(4096));
      const empty = path.join(directory, 'empty.7z');
      await FsUtil.writeFile(empty, Buffer.alloc(0));
      // Cut mid-archive: the signature and start-header survive, so the handler
      // gets far enough to seek to metadata that is no longer there.
      const truncated = path.join(directory, 'truncated.7z');
      const whole = await FsUtil.readFile(SEVEN_ZIP_ARCHIVE);
      await FsUtil.writeFile(truncated, whole.subarray(0, Math.floor(whole.length / 2)));

      for (const archivePath of [garbage, empty, truncated]) {
        await expect(
          sevenZip.listEntries({ inputFilename: archivePath, format: SevenZipFormat.SEVEN_ZIP }),
        ).rejects.toThrow(/is not a valid 7z archive/);
      }
      // A real, undamaged archive, opened as the wrong format. The addon never
      // guesses a format, so this is a caller mistake it has to report rather
      // than quietly correct.
      await expect(
        sevenZip.listEntries({ inputFilename: SEVEN_ZIP_ARCHIVE, format: SevenZipFormat.ZIP }),
      ).rejects.toThrow(/is not a valid zip archive/);
      await expect(
        sevenZip.listEntries({ inputFilename: ZIP_ARCHIVE, format: SevenZipFormat.SEVEN_ZIP }),
      ).rejects.toThrow(/is not a valid 7z archive/);
    });
  });

  test('it reports entry paths with forward slashes whatever the archive recorded', async () => {
    // This archive records a backslash-separated name, as archives written by
    // older Windows tools do. Reporting it verbatim is not an option that
    // exists: 7-Zip's zip handler rewrites separators to the host's before
    // kpidPath can be read, so on Windows a recorded `/` and a recorded `\`
    // arrive indistinguishable. Given that, the choice is between a path that
    // means the same thing everywhere and one that does not, and the addon
    // normalizes. openEntryReader() normalizes its input the same way, so a
    // listed path still resolves back to the entry it names.
    await withTempDir(async (directory) => {
      const archive = path.join(directory, 'backslash.zip');
      await writeStoredZip(archive, String.raw`dir\file.bin`, Buffer.from('windows-shaped name'));
      const entries = await sevenZip.listEntries({
        inputFilename: archive,
        format: SevenZipFormat.ZIP,
      });
      expect(entries.map((entry) => entry.entryPath)).toEqual(['dir/file.bin']);
    });
  });

  test('it numbers directory entries alongside the files they contain', async () => {
    // A directory entry is an item like any other, so the file that follows it
    // is item 1 -- not item 0, which is what an index recovered from a filtered
    // list would say. Callers do filter directories out, which is why the index
    // has to come from the archive rather than from a position in an array.
    await withTempDir(async (directory) => {
      const archive = path.join(directory, 'withdir.zip');
      await writeStoredZipEntries(archive, [
        { entryName: 'sub/', contents: Buffer.alloc(0) },
        { entryName: 'sub/file.bin', contents: Buffer.from('inside a directory') },
      ]);
      const entries = await sevenZip.listEntries({
        inputFilename: archive,
        format: SevenZipFormat.ZIP,
      });
      const files = entries.filter((entry) => !entry.isDirectory);
      expect(files.map((entry) => entry.entryPath)).toEqual(['sub/file.bin']);
      expect(files.map((entry) => entry.entryIndex)).toEqual([1]);
    });
  });
});

describe('openEntryReader', () => {
  test.each(MULTI_ENTRY_ARCHIVES)(
    'it extracts every entry of $label intact',
    async ({ format, archivePath }) => {
      const entries = await sevenZip.listEntries({ inputFilename: archivePath, format });
      for (const entry of entries) {
        const extracted = await drain(
          sevenZip.openEntryReader({
            inputFilename: archivePath,
            format,
            entryPath: entry.entryPath,
          }),
        );
        expect(extracted.length).toEqual(entry.size);
        expect(crc32Hex(extracted)).toEqual(entry.crc32);
      }
    },
  );

  test.each(MULTI_ENTRY_ARCHIVES)(
    'it extracts every entry of $label intact when given its index',
    async ({ format, archivePath }) => {
      // The fast path: the index is verified against the path and then used
      // directly, so the same bytes have to come out as without it.
      const entries = await sevenZip.listEntries({ inputFilename: archivePath, format });
      for (const entry of entries) {
        const extracted = await drain(
          sevenZip.openEntryReader({
            inputFilename: archivePath,
            format,
            entryPath: entry.entryPath,
            entryIndex: entry.entryIndex,
          }),
        );
        expect(extracted.length).toEqual(entry.size);
        expect(crc32Hex(extracted)).toEqual(entry.crc32);
      }
    },
  );

  test.each([
    { label: 'another entry', entryIndex: 3 },
    { label: 'past the end of the archive', entryIndex: 4096 },
    { label: 'not an integer', entryIndex: 1.5 },
    { label: 'negative', entryIndex: -1 },
  ])('it ignores an index pointing $label', async ({ entryIndex }) => {
    // Every one of these fails the path check, so the scan runs and the entry
    // named is the entry extracted. A wrong index can cost time, never bytes.
    const entries = await sevenZip.listEntries({
      inputFilename: SEVEN_ZIP_ARCHIVE,
      format: SevenZipFormat.SEVEN_ZIP,
    });
    const extracted = await drain(
      sevenZip.openEntryReader({
        inputFilename: SEVEN_ZIP_ARCHIVE,
        format: SevenZipFormat.SEVEN_ZIP,
        entryPath: entries[0].entryPath,
        entryIndex,
      }),
    );
    expect(extracted.length).toEqual(entries[0].size);
    expect(crc32Hex(extracted)).toEqual(entries[0].crc32);
  });

  test('it rejects an entry the archive does not have', async () => {
    // Same archive, same call, three ways of failing to name an entry that can
    // be extracted. A valid index does not rescue an unmatched path: the path is
    // what is asked for, and no item carries it, so it fails exactly as it does
    // without one. Naming nothing is how a nameless single-stream archive's only
    // member is addressed, so against an archive holding four it is ambiguous
    // rather than a shorthand for the first.
    await expect(
      drain(
        sevenZip.openEntryReader({
          inputFilename: SEVEN_ZIP_ARCHIVE,
          format: SevenZipFormat.SEVEN_ZIP,
          entryPath: 'nope',
        }),
      ),
    ).rejects.toThrow(/no entry named 'nope'/);
    await expect(
      drain(
        sevenZip.openEntryReader({
          inputFilename: SEVEN_ZIP_ARCHIVE,
          format: SevenZipFormat.SEVEN_ZIP,
          entryPath: 'nope',
          entryIndex: 0,
        }),
      ),
    ).rejects.toThrow(/no entry named 'nope'/);
    await expect(
      drain(
        sevenZip.openEntryReader({
          inputFilename: SEVEN_ZIP_ARCHIVE,
          format: SevenZipFormat.SEVEN_ZIP,
        }),
      ),
    ).rejects.toThrow(/no entry was named, and the archive holds 4 entries rather than one/);
  });

  test.each(SINGLE_STREAM_ARCHIVES)(
    'it extracts the stream of $label intact',
    async ({ format, archivePath }) => {
      // No entry is named: these formats record no name to match against, and
      // the addon extracts the one member the archive holds.
      const extracted = await drain(
        sevenZip.openEntryReader({ inputFilename: archivePath, format }),
      );
      // listEntries() reports no size or CRC32 for these formats, so the
      // expectations are the payload's own, shared by every one of them.
      expect(extracted.length).toEqual(SINGLE_STREAM_SIZE);
      expect(crc32Hex(extracted)).toEqual(SINGLE_STREAM_CRC32);
    },
  );

  test('it joins a split set back into the original bytes', async () => {
    const extracted = await drain(
      sevenZip.openEntryReader({
        inputFilename: SPLIT_FIRST_VOLUME,
        format: SevenZipFormat.SPLIT,
        entryPath: 'copy.7z',
      }),
    );
    expect(extracted.equals(await FsUtil.readFile(SPLIT_JOINED))).toEqual(true);
  });

  test('it extracts both entries across the disks of a multi-disk zip', async () => {
    // Same archive, same call, and the two members exercise the two different
    // pieces of arithmetic: `first.bin` is larger than a disk, so its
    // compressed bytes genuinely straddle a volume boundary, while `second.bin`
    // instead starts on a later disk, reached only by resolving its
    // disk-number-start against the joined stream. Listing alone would pass
    // either way, because the central directory lives entirely on the last disk.
    const extracted = await Promise.all(
      SPANNED_ENTRIES.map(
        async ({ entryPath }) =>
          await drain(
            sevenZip.openEntryReader({
              inputFilename: SPANNED_LAST_DISK,
              format: SevenZipFormat.ZIP,
              entryPath,
            }),
          ),
      ),
    );
    expect(extracted.map((buffer) => buffer.length)).toEqual(
      SPANNED_ENTRIES.map((entry) => entry.size),
    );
    expect(extracted.map((buffer) => crc32Hex(buffer))).toEqual(
      SPANNED_ENTRIES.map((entry) => entry.crc32),
    );
  });

  test('it drains an entry larger than the read-ahead bound byte-exactly', async () => {
    await withLargeArchive(async (largeArchive) => {
      const entries = await sevenZip.listEntries({
        inputFilename: largeArchive,
        format: SevenZipFormat.ZIP,
      });
      expect(entries.map((entry) => entry.size)).toEqual([LARGE_CONTENTS.length]);

      const extracted = await drain(
        sevenZip.openEntryReader({
          inputFilename: largeArchive,
          format: SevenZipFormat.ZIP,
          entryPath: 'stored.bin',
        }),
      );
      expect(extracted.length).toEqual(LARGE_CONTENTS.length);
      expect(crc32Hex(extracted)).toEqual(entries[0].crc32);
      expect(extracted.equals(LARGE_CONTENTS)).toEqual(true);
    });
  });

  test('it emits exactly the high-watermark until the entry runs out', async () => {
    // The size is a promise rather than a ceiling. 7-Zip's decoders emit output
    // at whatever size suits them -- a deflate block, an LZMA window -- so
    // without the producer accumulating to a full chunk before publishing, a
    // consumer sees whatever fell out of the decoder and a caller that sized its
    // reads gets nothing of the sort.
    //
    // Both an explicit size and the default are checked here because they take
    // different paths in index.ts: one is the caller's number, the other is
    // whatever Node chose for the stream, which this package deliberately does
    // not second-guess with a constant of its own.
    await withLargeArchive(async (largeArchive) => {
      const explicit = 128 * 1024;
      const sized = await collectChunks(
        sevenZip.openEntryReader({
          inputFilename: largeArchive,
          format: SevenZipFormat.ZIP,
          entryPath: 'stored.bin',
          highWaterMark: explicit,
        }),
      );
      expect(new Set(sized.slice(0, -1).map((chunk) => chunk.length))).toEqual(new Set([explicit]));
      expect(sized.at(-1)?.length).toEqual(LARGE_CONTENTS.length % explicit || explicit);
      expect(Buffer.concat(sized).equals(LARGE_CONTENTS)).toEqual(true);

      const readable = sevenZip.openEntryReader({
        inputFilename: largeArchive,
        format: SevenZipFormat.ZIP,
        entryPath: 'stored.bin',
      });
      const nodeDefault = readable.readableHighWaterMark;
      const defaulted = await collectChunks(readable);
      expect(new Set(defaulted.slice(0, -1).map((chunk) => chunk.length))).toEqual(
        new Set([nodeDefault]),
      );
      expect(Buffer.concat(defaulted).equals(LARGE_CONTENTS)).toEqual(true);
    });
  });

  test('it closes promptly while the producer is blocked on a full queue', async () => {
    // This is the test the addon's Pump::Cancel() exists for. One read lets the
    // producer race ahead until the read-ahead bound is reached, at which point
    // it is parked inside 7-Zip's Write() with nothing left to drain it.
    //
    // Nothing on this path waits for that thread -- teardown aborts it and drops
    // its reference -- so what is asserted is that destroy() completes, and
    // completes without needing the producer to have noticed anything yet.
    await withLargeArchive(async (largeArchive) => {
      const readable = sevenZip.openEntryReader({
        inputFilename: largeArchive,
        format: SevenZipFormat.ZIP,
        entryPath: 'stored.bin',
      });
      expect((await readable[Symbol.asyncIterator]().next()).done).toEqual(false);

      readable.destroy();
      await events.once(readable, 'close');
      expect(readable.destroyed).toEqual(true);
    });
  });

  test('it keeps serving new streams after earlier ones are abandoned', async () => {
    // Nothing destroys the abandoned streams while anything is being asserted.
    // This asserts only that walking away mid-entry does not wedge the addon for
    // the streams that follow -- it does NOT prove the finalizer reclaims
    // anything, because Vitest runs without --expose-gc so no finalizer is
    // forced to run. Reclamation is a leak invariant, and the task that owns
    // those has to prove it with a thread/handle count under a forced GC.
    await withLargeArchive(async (largeArchive) => {
      const abandoned: stream.Readable[] = [];
      for (let i = 0; i < 8; i++) {
        const readable = sevenZip.openEntryReader({
          inputFilename: largeArchive,
          format: SevenZipFormat.ZIP,
          entryPath: 'stored.bin',
        });
        abandoned.push(readable);
        const first = await readable[Symbol.asyncIterator]().next();
        expect(first.done).toEqual(false);
      }

      const extracted = await drain(
        sevenZip.openEntryReader({
          inputFilename: largeArchive,
          format: SevenZipFormat.ZIP,
          entryPath: 'stored.bin',
        }),
      );
      expect(extracted.length).toEqual(LARGE_CONTENTS.length);

      // Only now, with every assertion behind us: each of these is parked on a
      // full queue with nobody draining it, so its producer thread holds the
      // archive open until something tells it to stop, and Windows will not let
      // withLargeArchive remove the directory underneath an open handle.
      await Promise.all(
        abandoned.map(async (readable) => {
          readable.destroy();
          await events.once(readable, 'close');
        }),
      );
    });
  });

  test('it accepts an entry path spelled with either separator', async () => {
    // The archive records a backslash and listEntries reports a forward slash,
    // so the round trip works on its own. What this pins down is the other half
    // of the contract: a caller holding the name as the archive spelled it --
    // read out of the archive by another tool, or carried over from an older
    // listing -- still resolves to the same entry rather than being told the
    // archive does not have it.
    await withTempDir(async (directory) => {
      const archive = path.join(directory, 'backslash.zip');
      const contents = Buffer.from('either spelling');
      await writeStoredZip(archive, String.raw`dir\file.bin`, contents);

      const extracted = await Promise.all(
        [String.raw`dir\file.bin`, 'dir/file.bin'].map(
          async (entryPath) =>
            await drain(
              sevenZip.openEntryReader({
                inputFilename: archive,
                format: SevenZipFormat.ZIP,
                entryPath,
              }),
            ),
        ),
      );
      expect(extracted.map((buffer) => buffer.toString())).toEqual([
        contents.toString(),
        contents.toString(),
      ]);
    });
  });

  test('it rejects an entry whose compressed data is corrupt', async () => {
    // The failure mode that matters most to a caller: a stream that ends early
    // and resolves looks exactly like a short file, so a checksum taken over it
    // would be recorded as if it were the entry's own. It has to reject.
    //
    // The damage is past the signature header, so the archive still lists --
    // every entry's name, size, and CRC32 are readable, and only the bytes are
    // gone. Listing succeeding is what makes the extraction assertion meaningful.
    await withTempDir(async (directory) => {
      const corrupt = path.join(directory, 'corrupt.7z');
      const whole = Buffer.from(await FsUtil.readFile(SEVEN_ZIP_ARCHIVE));
      for (let i = 32; i < 48; i++) {
        whole[i] ^= 0x5a;
      }
      await FsUtil.writeFile(corrupt, whole);

      const entries = await sevenZip.listEntries({
        inputFilename: corrupt,
        format: SevenZipFormat.SEVEN_ZIP,
      });
      expect(entries.map((entry) => entry.entryPath)).toEqual(['1kb', '2kb', '3kb', '4kb']);
      for (const entry of entries) {
        await expect(
          drain(
            sevenZip.openEntryReader({
              inputFilename: corrupt,
              format: SevenZipFormat.SEVEN_ZIP,
              entryPath: entry.entryPath,
            }),
          ),
        ).rejects.toThrow(/its compressed data is corrupt|it failed its CRC check/);
      }
    });
  });

  test('it rejects an entry it has no way to decode', async () => {
    // Two archives that differ only in the one header field that makes them
    // undecodable, listed and extracted the same way:
    //
    //   - Method 77 is registered to nothing, here or upstream, so it stands in
    //     for any archive whose codec this build does not carry.
    //   - The encrypted-bit entry has no decryptor to reach and no password to
    //     supply, because this build is compiled with Z7_NO_CRYPTO.
    //
    // Both list normally in the same way, and for the same reason: a method
    // number and an encryption flag are metadata, and 7-Zip only goes looking
    // for a decoder once extraction asks for the bytes. A caller therefore
    // learns about encryption up front -- that is what `isEncrypted` is for --
    // and one that extracts anyway gets an error rather than the ciphertext.
    await withTempDir(async (directory) => {
      const unsupported = path.join(directory, 'unsupported-method.zip');
      await writeStoredZip(unsupported, 'a.bin', Buffer.from('never decoded'), { method: 77 });
      const encrypted = path.join(directory, 'encrypted.zip');
      await writeStoredZip(encrypted, 'a.bin', Buffer.from('never decrypted'), { flags: 1 });

      const [unsupportedEntries, encryptedEntries] = await Promise.all(
        [unsupported, encrypted].map(
          async (archive) =>
            await sevenZip.listEntries({ inputFilename: archive, format: SevenZipFormat.ZIP }),
        ),
      );
      expect(unsupportedEntries.map((entry) => entry.entryPath)).toEqual(['a.bin']);
      expect(unsupportedEntries.map((entry) => entry.isEncrypted)).toEqual([false]);
      expect(encryptedEntries.map((entry) => entry.entryPath)).toEqual(['a.bin']);
      expect(encryptedEntries.map((entry) => entry.isEncrypted)).toEqual([true]);

      await expect(
        drain(
          sevenZip.openEntryReader({
            inputFilename: unsupported,
            format: SevenZipFormat.ZIP,
            entryPath: 'a.bin',
          }),
        ),
      ).rejects.toThrow(/its compression method is not supported by this build/);
      await expect(
        drain(
          sevenZip.openEntryReader({
            inputFilename: encrypted,
            format: SevenZipFormat.ZIP,
            entryPath: 'a.bin',
          }),
        ),
      ).rejects.toThrow(/it is encrypted, and encrypted entries are not supported/);
    });
  });

  test.each(LARGE_ENTRY_ARCHIVES)(
    'it drains $label, whose decoder fills the read-ahead queue in one call',
    async ({ format, archivePath }) => {
      // A regression test for a deadlock in the addon's ChunkQueue, not a
      // throughput test.
      //
      // LZMA2's decoder writes up to `_outStep` -- 1 MiB, see
      // deps/7zip/CPP/7zip/Compress/LzmaDecoder.cpp -- into the output sink per
      // call, and the queue's read-ahead bound is also about 1 MiB. So a single
      // decoder call can push the queue from empty to completely full. The
      // producer then parks in Write() waiting for room, and a consumer that
      // had already been told there was nothing to read parks waiting to be
      // woken. Before the fix, the wake-up was only sent once Write() returned,
      // which on this path it never does: the two threads wait on each other
      // and the stream hangs forever.
      //
      // The archive is small but the entry is not, so the assertion that
      // matters is simply that this resolves at all. The explicit timeout is
      // what turns a regression into a failure instead of a hung suite.
      const extracted = await drain(
        sevenZip.openEntryReader({
          inputFilename: archivePath,
          format,
          entryPath: LARGE_ENTRY_PATH,
        }),
      );
      expect(extracted.length).toEqual(LARGE_ENTRY_SIZE);
      // Position-dependent, so a torn or reordered queue shows up here rather
      // than passing on length alone.
      expect(
        extracted.equals(Buffer.from(Array.from({ length: LARGE_ENTRY_SIZE }, (_, i) => i % 251))),
      ).toEqual(true);
    },
    30_000,
  );
});
