import crypto from 'node:crypto';
import events from 'node:events';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type stream from 'node:stream';
import zlib from 'node:zlib';

import { afterAll, beforeAll, describe, expect, test } from 'vitest';

import { extractEntry, listEntries, SevenZipFormat } from '../index.js';

const FIXTURE_DIR = path.join('packages', '7zip', 'test', 'fixtures');

function fixtureDir(format: string): string[] {
  return fs
    .readdirSync(path.join(FIXTURE_DIR, format))
    .toSorted((a, b) => a.localeCompare(b))
    .map((file) => path.join(FIXTURE_DIR, format, file));
}

const SEVEN_ZIP_FIXTURES = fixtureDir('7z');

/**
 * Zips whose members use compression method 93, WinZip's Zstandard. They are
 * zips rather than `.7z` because zstd is not a 7z method: 7-Zip registers no
 * codec for it, and the addon reaches its decoder only through
 * ZipHandler.cpp's branch for method 93.
 */
const ZIP_FIXTURES = fixtureDir('zip');

interface MultiEntryArchive {
  label: string;
  format: SevenZipFormat;
  archivePath: string;
}

/**
 * Every archive holding the same four entries: `1kb` through `4kb`. The `.7z`
 * fixtures share one payload; the zstd zips carry a compressible one instead,
 * so that method 93 exercises zstd's literal and sequence decoders rather than
 * emitting raw blocks. Nothing here compares bytes across archives -- each
 * entry is checked against the CRC32 its own archive records.
 */
const MULTI_ENTRY_ARCHIVES: MultiEntryArchive[] = [
  ...SEVEN_ZIP_FIXTURES.map((fixture) => ({
    label: path.relative(FIXTURE_DIR, fixture),
    format: SevenZipFormat.SEVEN_ZIP,
    archivePath: fixture,
  })),
  ...ZIP_FIXTURES.map((fixture) => ({
    label: path.relative(FIXTURE_DIR, fixture),
    format: SevenZipFormat.ZIP,
    archivePath: fixture,
  })),
];

interface SingleStreamArchive {
  label: string;
  format: SevenZipFormat;
  archivePath: string;
}

/**
 * Formats that wrap one nameless stream instead of a directory of entries. They
 * all compress the same 4 KiB payload, so one CRC32 covers every one of them.
 */
const SINGLE_STREAM_ARCHIVES: SingleStreamArchive[] = [
  ...fixtureDir('z').map((archivePath) => ({
    label: path.relative(FIXTURE_DIR, archivePath),
    format: SevenZipFormat.Z,
    archivePath,
  })),
  ...fixtureDir('bz2').map((archivePath) => ({
    label: path.relative(FIXTURE_DIR, archivePath),
    format: SevenZipFormat.BZIP2,
    archivePath,
  })),
  ...fixtureDir('lzma').map((archivePath) => ({
    label: path.relative(FIXTURE_DIR, archivePath),
    format: SevenZipFormat.LZMA,
    archivePath,
  })),
];

// The payload every single-stream fixture holds, as generated by
// `fixtures/generate.sh`.
const SINGLE_STREAM_SIZE = 4096;
const SINGLE_STREAM_CRC32 = '266df1c3';

/**
 * `7z/copy.7z` sliced into 4 KiB volumes by `split`. Only the first slice is
 * ever named: 7-Zip's `Split` handler derives `.002`, `.003` and so on itself.
 * Listing it yields one entry -- the slices joined back together -- which is why
 * this is not part of {@link MULTI_ENTRY_ARCHIVES} despite being built from an
 * archive that holds four.
 */
const SPLIT_FIRST_VOLUME = path.join(FIXTURE_DIR, 'split', 'copy.7z.001');
const SPLIT_JOINED = path.join(FIXTURE_DIR, '7z', 'copy.7z');

/**
 * A true multi-disk zip from Info-ZIP's `zip -s`, which is a different thing
 * from the byte-sliced `split/` fixture: the final disk is named `.zip` and
 * carries the central directory, the earlier ones are `.z01`/`.z02`, and the
 * first opens with the 4-byte spanning marker.
 *
 * Only the last disk is named here. It is the one holding the central
 * directory, and it is the disk 7-Zip expects to be handed; it walks back to
 * `.z01` and `.z02` through the addon's open callback.
 */
const SPANNED_LAST_DISK = path.join(FIXTURE_DIR, 'spanned', 'spanned.zip');
/**
 * Both members, in archive order. `first.bin` runs past the end of the second
 * disk, so `second.bin`'s local header begins on disk 2 and its
 * central-directory record carries `disk-number-start=2` with a local-header
 * offset relative to that disk rather than to the joined stream. Resolving that
 * pair back to an absolute offset is the arithmetic a single-member archive
 * never exercises.
 */
const SPANNED_ENTRIES = [
  { entryPath: 'first.bin', size: 140_000, crc32: '211e7a1d' },
  { entryPath: 'second.bin', size: 40_000, crc32: '9812a804' },
];

async function drain(readable: stream.Readable): Promise<Buffer> {
  const chunks: Buffer[] = [];
  for await (const chunk of readable) {
    chunks.push(chunk as Buffer);
  }
  return Buffer.concat(chunks);
}

// Node's crypto has no 'crc32' digest, but zlib.crc32() has been available
// since Node v20.15.0, comfortably below this package's engines floor.
function crc32Hex(buffer: Buffer): string {
  return zlib.crc32(buffer).toString(16).padStart(8, '0');
}

/**
 * Write a single-entry ZIP that stores its payload uncompressed (method 0).
 * Stored entries need no encoder, so a large archive can be produced here at
 * test time rather than committed as a binary fixture.
 *
 * With `hasSpanMarker`, the file is prefixed with NSignature::kSpan, the four bytes
 * `zip -s` writes at the front of a spanned archive. It is otherwise a perfectly
 * ordinary single-volume ZIP -- the marker alone is what puts 7-Zip's Zip
 * handler onto its span-mode path.
 */
function writeStoredZip(
  filePath: string,
  entryName: string,
  contents: Buffer,
  hasSpanMarker = false,
): void {
  const name = Buffer.from(entryName, 'utf8');
  const crc = zlib.crc32(contents);
  const size = contents.length;

  const prefix = Buffer.alloc(hasSpanMarker ? 4 : 0);
  if (hasSpanMarker) {
    prefix.writeUInt32LE(0x08_07_4b_50, 0); // NSignature::kSpan
  }

  const localHeader = Buffer.alloc(30);
  localHeader.writeUInt32LE(0x04_03_4b_50, 0); // local file header signature
  localHeader.writeUInt16LE(20, 4); // version needed to extract
  localHeader.writeUInt32LE(crc, 14);
  localHeader.writeUInt32LE(size, 18); // compressed size
  localHeader.writeUInt32LE(size, 22); // uncompressed size
  localHeader.writeUInt16LE(name.length, 26);

  const centralHeader = Buffer.alloc(46);
  centralHeader.writeUInt32LE(0x02_01_4b_50, 0); // central directory signature
  centralHeader.writeUInt16LE(20, 4); // version made by
  centralHeader.writeUInt16LE(20, 6); // version needed to extract
  centralHeader.writeUInt32LE(crc, 16);
  centralHeader.writeUInt32LE(size, 20);
  centralHeader.writeUInt32LE(size, 24);
  centralHeader.writeUInt16LE(name.length, 28);
  centralHeader.writeUInt32LE(prefix.length, 42); // local header offset

  const endOfCentralDirectory = Buffer.alloc(22);
  endOfCentralDirectory.writeUInt32LE(0x06_05_4b_50, 0); // end of central directory signature
  endOfCentralDirectory.writeUInt16LE(1, 8); // entries on this disk
  endOfCentralDirectory.writeUInt16LE(1, 10); // entries total
  endOfCentralDirectory.writeUInt32LE(centralHeader.length + name.length, 12);
  endOfCentralDirectory.writeUInt32LE(prefix.length + localHeader.length + name.length + size, 16);

  const handle = fs.openSync(filePath, 'w');
  try {
    for (const chunk of [
      prefix,
      localHeader,
      name,
      contents,
      centralHeader,
      name,
      endOfCentralDirectory,
    ]) {
      fs.writeSync(handle, chunk);
    }
  } finally {
    fs.closeSync(handle);
  }
}

describe('listEntries', () => {
  test('it has fixtures to test', () => {
    expect(SEVEN_ZIP_FIXTURES.length).toEqual(10);
    expect(ZIP_FIXTURES.length).toEqual(2);
    expect(MULTI_ENTRY_ARCHIVES.length).toEqual(12);
    expect(SINGLE_STREAM_ARCHIVES.length).toEqual(5);
  });

  test.each(MULTI_ENTRY_ARCHIVES)(
    'it lists the four entries in $label',
    async ({ format, archivePath }) => {
      const entries = await listEntries(archivePath, format);
      expect(entries.map((entry) => entry.index)).toEqual([0, 1, 2, 3]);
      expect(entries.map((entry) => entry.entryPath)).toEqual(['1kb', '2kb', '3kb', '4kb']);
      expect(entries.map((entry) => entry.size)).toEqual([1024, 2048, 3072, 4096]);
      expect(entries.every((entry) => /^[\da-f]{8}$/.test(entry.crc32 ?? ''))).toEqual(true);
      expect(entries.every((entry) => !entry.isDirectory)).toEqual(true);
      expect(entries.every((entry) => !entry.isEncrypted)).toEqual(true);
    },
  );

  test.each(SINGLE_STREAM_ARCHIVES)(
    'it lists one nameless entry in $label',
    async ({ format, archivePath }) => {
      const entries = await listEntries(archivePath, format);
      expect(entries.length).toEqual(1);
      expect(entries[0].index).toEqual(0);
      // None of these containers records the member's name, size, or CRC32, so
      // the addon has nothing to report for them. The decompressed bytes are
      // still exact; `extractEntry` proves that.
      expect(entries[0].entryPath).toBeUndefined();
      // Undefined, not 0: these formats record no length, and 0 is a real
      // length an empty member could legitimately have.
      expect(entries[0].size).toBeUndefined();
      expect(entries[0].crc32).toBeUndefined();
      expect(entries[0].isDirectory).toEqual(false);
      expect(entries[0].isEncrypted).toEqual(false);
    },
  );

  test('it finds the rest of a split set from the first volume alone', async () => {
    // The whole point of the Split handler: `copy.7z.002` and `copy.7z.003` are
    // never named here. 7-Zip derives them from `.001` and pulls them through
    // the addon's IArchiveOpenVolumeCallback, which is also the interface
    // SplitHandler.cpp:126-133 refuses to open without.
    const entries = await listEntries(SPLIT_FIRST_VOLUME, SevenZipFormat.SPLIT);
    expect(entries.map((entry) => entry.entryPath)).toEqual(['copy.7z']);
    // One entry, whose size is every slice added together -- the joined archive,
    // not the four entries inside it.
    expect(entries.map((entry) => entry.size)).toEqual([fs.statSync(SPLIT_JOINED).size]);
  });

  test('it finds the earlier disks of a multi-disk zip from the last alone', async () => {
    // `spanned.z01` and `spanned.z02` are never named. Handing over only the
    // disk that carries the central directory is what a caller naturally has,
    // and ordering volumes by hand -- which used to be required, and silently
    // mis-extracted when wrong -- is no longer possible to get wrong.
    const entries = await listEntries(SPANNED_LAST_DISK, SevenZipFormat.ZIP);
    expect(entries.map((entry) => entry.entryPath)).toEqual(
      SPANNED_ENTRIES.map((entry) => entry.entryPath),
    );
    expect(entries.map((entry) => entry.size)).toEqual(SPANNED_ENTRIES.map((entry) => entry.size));
    expect(entries.map((entry) => entry.crc32)).toEqual(
      SPANNED_ENTRIES.map((entry) => entry.crc32),
    );
  });

  test('it opens a single-volume zip that carries the span marker', async () => {
    // Regression test for a process-killing SIGSEGV, not a correctness nicety.
    // 7-Zip's CInArchive::Open has two ReadVols() call sites; only the first is
    // guarded by a non-null callback, and the span-mode one is not. Reaching it
    // with a null IArchiveOpenCallback dereferences null in ReadVols (ZipIn.cpp
    // :2337).
    //
    // Verified to exit 139 against a build that passes nullptr, and to pass
    // against the shipped one. If this ever regresses it takes the whole Vitest
    // worker down rather than failing an assertion -- that is the nature of the
    // bug, and a loud death is still a caught regression.
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'igir-7zip-span-'));
    try {
      const archive = path.join(directory, 'span.zip');
      writeStoredZip(archive, 'a.txt', Buffer.from('hello span mode'), true);
      const entries = await listEntries(archive, SevenZipFormat.ZIP);
      expect(entries.length).toBeGreaterThanOrEqual(1);
      expect(entries[0].entryPath).toEqual('a.txt');
    } finally {
      fs.rmSync(directory, { recursive: true, force: true });
    }
  });

  test('it rejects a missing file', async () => {
    await expect(
      listEntries(path.join(FIXTURE_DIR, 'nope.7z'), SevenZipFormat.SEVEN_ZIP),
    ).rejects.toThrow();
  });

  test('it rejects an empty path', async () => {
    await expect(listEntries('', SevenZipFormat.SEVEN_ZIP)).rejects.toThrow();
  });
});

describe('extractEntry', () => {
  test.each(MULTI_ENTRY_ARCHIVES)(
    'it extracts every entry of $label intact',
    async ({ format, archivePath }) => {
      const entries = await listEntries(archivePath, format);
      for (const entry of entries) {
        const extracted = await drain(extractEntry(archivePath, format, entry.index));
        expect(extracted.length).toEqual(entry.size);
        expect(crc32Hex(extracted)).toEqual(entry.crc32);
      }
    },
  );

  test('it accepts an entry path as well as an index', async () => {
    const archivePath = SEVEN_ZIP_FIXTURES[0];
    const byIndex = await drain(extractEntry(archivePath, SevenZipFormat.SEVEN_ZIP, 2));
    const byPath = await drain(extractEntry(archivePath, SevenZipFormat.SEVEN_ZIP, '3kb'));
    expect(byPath.length).toEqual(3072);
    expect(byPath.equals(byIndex)).toEqual(true);
  });

  test('it rejects an unknown entry path', async () => {
    await expect(
      drain(extractEntry(SEVEN_ZIP_FIXTURES[0], SevenZipFormat.SEVEN_ZIP, 'nope')),
    ).rejects.toThrow(/no entry named nope/);
  });

  test('it rejects an out-of-range entry index', async () => {
    await expect(
      drain(extractEntry(SEVEN_ZIP_FIXTURES[0], SevenZipFormat.SEVEN_ZIP, 999)),
    ).rejects.toThrow();
  });

  test.each(SINGLE_STREAM_ARCHIVES)(
    'it extracts the stream of $label intact',
    async ({ format, archivePath }) => {
      const extracted = await drain(extractEntry(archivePath, format, 0));
      // listEntries() reports no size or CRC32 for these formats, so the
      // expectations are the payload's own, shared by every one of them.
      expect(extracted.length).toEqual(SINGLE_STREAM_SIZE);
      expect(crc32Hex(extracted)).toEqual(SINGLE_STREAM_CRC32);
    },
  );

  test('it joins a split set back into the original bytes', async () => {
    const extracted = await drain(extractEntry(SPLIT_FIRST_VOLUME, SevenZipFormat.SPLIT, 0));
    expect(extracted.equals(fs.readFileSync(SPLIT_JOINED))).toEqual(true);
  });

  test.each(SPANNED_ENTRIES.map((entry, index) => ({ ...entry, index })))(
    'it extracts $entryPath across the disks of a multi-disk zip',
    async ({ index, size, crc32 }) => {
      // `first.bin` is larger than a disk, so its compressed bytes genuinely
      // straddle a volume boundary; `second.bin` instead starts on a later disk,
      // reached only by resolving its disk-number-start against the joined
      // stream. Listing alone would pass either way, because the central
      // directory lives entirely on the last disk.
      const extracted = await drain(extractEntry(SPANNED_LAST_DISK, SevenZipFormat.ZIP, index));
      expect(extracted.length).toEqual(size);
      expect(crc32Hex(extracted)).toEqual(crc32);
    },
  );

  // Comfortably more than the addon's 1 MiB ring buffer, so the producer thread
  // blocks and the buffer wraps many times over, while staying small enough to
  // build and drain quickly in CI.
  const LARGE_CONTENTS = crypto.randomBytes(8 * 1024 * 1024);
  let tempDir: string;
  let largeArchive: string;

  beforeAll(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'igir-7zip-'));
    largeArchive = path.join(tempDir, 'stored.zip');
    writeStoredZip(largeArchive, 'stored.bin', LARGE_CONTENTS);
  });

  afterAll(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  test('it drains an entry larger than the ring buffer byte-exactly', async () => {
    const entries = await listEntries(largeArchive, SevenZipFormat.ZIP);
    expect(entries.map((entry) => entry.size)).toEqual([LARGE_CONTENTS.length]);

    const extracted = await drain(extractEntry(largeArchive, SevenZipFormat.ZIP, 0));
    expect(extracted.length).toEqual(LARGE_CONTENTS.length);
    expect(crc32Hex(extracted)).toEqual(entries[0].crc32);
    expect(extracted.equals(LARGE_CONTENTS)).toEqual(true);
  });

  test('it closes promptly while the producer is blocked on a full buffer', async () => {
    // This is the test the addon's Pump::Cancel() exists for. One read lets the
    // producer race ahead until the 1 MiB ring buffer fills, at which point it
    // is parked inside 7-Zip's Write() with nothing left to drain it. Tearing
    // down joins that thread, so without an abort that wakes it the join never
    // returns and this hangs until the suite times out.
    const readable = extractEntry(largeArchive, SevenZipFormat.ZIP, 0);
    expect((await readable[Symbol.asyncIterator]().next()).done).toEqual(false);

    readable.destroy();
    await events.once(readable, 'close');
    expect(readable.destroyed).toEqual(true);
  });

  test('it keeps serving new streams after earlier ones are abandoned', async () => {
    // Nothing here destroys the abandoned streams. This asserts only that
    // walking away mid-entry does not wedge the addon for the streams that
    // follow -- it does NOT prove the finalizer reclaims anything, because
    // Vitest runs without --expose-gc so no finalizer is forced to run.
    // Reclamation is a leak invariant, and the task that owns those has to
    // prove it with a thread/handle count under a forced GC.
    for (let i = 0; i < 8; i++) {
      const abandoned = extractEntry(largeArchive, SevenZipFormat.ZIP, 0);
      const first = await abandoned[Symbol.asyncIterator]().next();
      expect(first.done).toEqual(false);
    }

    const extracted = await drain(extractEntry(largeArchive, SevenZipFormat.ZIP, 0));
    expect(extracted.length).toEqual(LARGE_CONTENTS.length);
  });
});
