#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Change to the project's root directory
cd "$(dirname -- "$0")/.." || exit 1

# Ensure node is available (same as asciinema-rec.sh)
if [[ ! -x "$(command -v node)" ]]; then
  if [[ ! -x "$(command -v nvm)" && -f ~/.nvm/nvm.sh ]]; then
    . ~/.nvm/nvm.sh
  fi
  if [[ ! -x "$(command -v nvm)" ]]; then
    nvm use || exit 1
  fi
fi
node --version &> /dev/null || exit 1


# Follow the linter
npm run lint:fix


# Update the help text in README.md
README="README.md"
README_BEFORE=$(cat "${README}")
./scripts/update-readme-help.sh
README_AFTER=$(cat "${README}")
if [[ "${README_AFTER}" != "${README_BEFORE}" ]]; then
  # TODO(cemmer): way to not commit the entire file when the help text changes?
  git add "${README}"
fi
