name: Auto-Merge Rebaser

on:
  push:
    branches:
      - 'main'
  schedule:
    # Every hour
    - cron: '0 * * * *'

jobs:
  # NOTE(cemmer): this requires PRs to be auto-merge enabled, so this won't run for Renovate PRs
  #   https://github.com/adRise/update-pr-branch/blob/00f3aa159dd699e5e88ae904a6157eb83c482319/src/lib/github.js#L160-L162
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: adRise/update-pr-branch@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: 'main'
          required_approval_count: 0
          require_passed_checks: false
          # Oldest pull request
          sort: 'created'
          direction: 'asc'
