name: GitHub Lock Issues

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '30'
          issue-comment: |
            ## :lock: Inactive issue lock
            This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
          pr-inactive-days: '30'
          pr-comment: |
            ## :lock: Inactive pull request lock
            This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
