name: GitHub Stale Issues

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-issue-stale: 14
          days-before-pr-stale: -1
          days-before-close: 14
          stale-issue-message: 'This issue is stale because it has been open 14 days with no activity. Comment or this will be automatically closed in 14 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 14 days with no activity. Only repository collaborators will be able to re-open this issue.'
          stale-issue-label: 'stale'
          only-labels: 'question'
