name: GitHub Labeler

on:
  pull_request:
    types:
      - opened
      - synchronize  # HEAD has changed, e.g. a push happened
      - reopened
#    paths:
#      - .github/labels.yml

  push:
    branches:
      - 'main'
    paths:
      - .github/labels.yml

jobs:
  dry-run:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          dry-run: true
          token: ${{ secrets.GITHUB_TOKEN }}

  sync:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: b4b4r07/github-labeler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
