name: Node.js Package Update Holds

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  path-filter:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            changes:
              - 'package*.json'

  node-install-hold:
    needs:
      - path-filter
    if: ${{ needs.path-filter.outputs.changes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - id: install-hold
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          {
            echo "JSON<<$EOF"
            npm run install:hold
            echo "$EOF"
          } >> "${GITHUB_OUTPUT}"
      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## :arrow_down:
            ```json
            ${{ steps.install-hold.outputs.JSON }}
            ```
            _Comment generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}) workflow._
          mode:
          comment-tag: package-hold
