name: Node.js Branch Exec

on:
  # pull_request_target required for pull-requests:write permission on fork PRs
  pull_request_target:
    types:
      # - edited  # PR's base branch was changed
      - opened
      - reopened
      - synchronize  # PR's branch was edited (i.e. new commits)
      - closed
    paths:
      - '*'
      - 'src/**'
      - 'test/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  npm-exec-test:
    if: github.event.action != 'closed'
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]
    steps:
      - uses: volta-cli/action@v4
      - env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: npm exec --loglevel verbose --yes -- "github:${{ github.event.pull_request.head.repo.full_name }}#${HEAD_REF}" --help

  npm-exec:
    if: github.event.action != 'closed'
    needs:
      - npm-exec-test
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## :test_tube: Branch testing instructions
            This pull request can be tested locally with the following command:
            ```shell
            npm exec --yes -- "github:${{ github.event.pull_request.head.repo.full_name }}#${{ github.event.pull_request.head.ref }}" [commands..] [options]
            ```
            _Comment generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}) workflow._
          comment-tag: npm-exec

  npm-exec-comment-update:
    if: github.event.action == 'closed' && github.event.pull_request.merged
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## :test_tube: Branch testing instructions
            This pull request has been merged, its base branch can be tested locally with the following command:
            ```shell
            npm exec --yes -- "github:${{ github.event.pull_request.base.repo.full_name }}#${{ github.event.pull_request.base.ref }}" [commands..] [options]
            ```
            _Comment generated by the [${{ github.workflow }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}) workflow._
          comment-tag: npm-exec
          mode: recreate
