name: Scoop Test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (refs/heads/<branch>, refs/tags/<tag>, etc.) or SHA'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.ref || github.ref }}
  cancel-in-progress: true

env:
  ref: ${{ inputs.ref || github.sha || github.ref }}

jobs:
  path-filter:
    permissions:
      pull-requests: read # dorny/paths-filter
    runs-on: ubuntu-latest
    outputs:
      should-test: ${{ steps.filter.outputs.should-test }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ env.ref }}
      - id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            should-test:
              - '.github/workflows/scoop-test.yml'
              - 'bucket/**'

  # The manifest validation is architecture-agnostic, so only run it once
  scoop-validate:
    needs:
      - path-filter
    if: ${{ needs.path-filter.outputs.should-test == 'true' }}
    permissions:
      contents: read # actions/checkout
      pull-requests: read # explicitly deny ScoopInstaller/GithubActions comment and label permissions
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ env.ref }}
      - uses: ScoopInstaller/GithubActions@37a17b993c5ae4ae44fdc47379eb67010c800323 # 2.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          THROW_ERROR: '1'

  scoop-test:
    name: scoop-test (${{ matrix.os }})
    needs:
      - path-filter
    if: ${{ needs.path-filter.outputs.should-test == 'true' }}
    permissions:
      contents: read # actions/checkout
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, windows-11-arm ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ env.ref }}
      - shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          Invoke-WebRequest -UseBasicParsing -Uri 'https://get.scoop.sh' -OutFile install.ps1
          .\install.ps1 -RunAsAdmin
          $env:PATH = "$env:USERPROFILE\scoop\shims;$env:PATH"

          scoop install .\bucket\igir.json

          igir --help

  # !!! This check should be required by GitHub !!!
  scoop-status-check:
    needs:
      - path-filter
      - scoop-validate
      - scoop-test
    if: always()
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: scoop-validate, scoop-test
